### ISSUE TITLE
Неустойчивость длительности свечения светодиода

### ISSUE THREAD

**Issue by KimIV** [githubniko/LatencyMeter#1]
Я собрал Вашу схему на макетке для протестировать и залил последнюю версию скетча от 02.01.2024.

![01_1](https://github.com/githubniko/LatencyMeter/assets/25266563/d8a600b9-952b-4200-b348-0b264613982d)

Схема сразу заработала в паре со скетчем, но напряг один момент. Я полагал так, что если светодиод направить на фоторезистор без посредников, то должна быть нулевая задержка. Но на индикаторе я увидел скачущие цифры от 0 до 3. Это было бОльшую часть времени наблюдения в течение нескольких десятков секунд. Но иногда (очень редко) проскакивали цифры 4, 5, 6 и 7. Я решил посмотреть осциллографом сигналы на светодиоде и фоторезисторе. Вот точки контроля по Вашей схеме.

![01_2](https://github.com/githubniko/LatencyMeter/assets/25266563/d7fdd451-4d8c-4c2d-aee0-e4a898b9ec8c)

И наблюдал интересную картину. Время свечения светодиода плавно увеличивалось. Потом резко уменьшалось и снова плавно увеличивалось. Но иногда резко увеличивалось и также резко уменьшалось. Вот ссылка на видео https://youtu.be/JZO6ssp1RjM

Тогда я решил откатиться к Вашей первоначальной версии latencymeter_old.hex Ситуация с нулевой задержкой на этой прошивке намного лучше. Цифры на индикаторе видны только 0 и 1. И время свечения светодиода уже не имеет плавных нарастаний, а есть только скачки. Вот скрины минимальной и максимальной длительностей свечения светодиода (жёлтый луч).

![01_3](https://github.com/githubniko/LatencyMeter/assets/25266563/7e6d9d99-a07b-46b8-ae2b-b6a1170a284c)
![01_4](https://github.com/githubniko/LatencyMeter/assets/25266563/0e0bcc03-16a7-474a-8fd7-df0db12e4dbf)

А также ссылка на видео https://youtu.be/XXs31W97c6k

PS. Я пока только обрисовал проблему. Изучаю Ваши исходники и пытаюсь понять, где собака порылась...

**Comment by KimIV** [comment]
Ну и по ходу дела ещё один нюанс, на который я обратил внимание. У меня почему-то нет вот этой задержки между момент зажигания светодиода и моментом начала реакции фоторезистора. Вот скрин из Вашего видео по сборке. А мои скрины в предыдущем сообщении.

![02_1](https://github.com/githubniko/LatencyMeter/assets/25266563/005f6e6b-9c19-423d-b3fe-4f6d366e0abc)

**Comment by githubniko** [comment]
Эта задержка на последнем скриншоте не нужна. Почему она у меня была на видео не стал выяснять. Что касается плавного нарастания на осциллограммах, то оно у Вас ~0.8мс, у меня было на старой прошивке ~0.03мс. Новую прошивку не смотрел осциллографом. После праздников проверю обязательно.
Попробуйте закомментировать ресурсную функцию расчета медианы в latencymeter.h:90. Так же можно попробовать исключить конденсатор С1 на фоторезисторе. Еще важно, чтобы на фоторезистор не поступал лишний свет.

**Comment by githubniko** [comment]
Почему-то у Вас напряжение на фотодиоде очень большое. Должно быть стартовое +0.5В. Установлено ли Uref = 3.3 ?

**Comment by KimIV** [comment]
> Эта задержка на последнем скриншоте не нужна.

Это-то как раз понятно. Даже если бы она была, её необходимо было бы компенсировать программно. Просто я шёл по Вашим следам и удивлялся, почему мои "деревья растут вверх ногами" ))) Были даже сомнения сначала, может я где напортачил и что-то сделал не так. Какое-то время потратил на перепроверки. Ну и потом решил Ваше внимание обратить на это...

> Что касается плавного нарастания на осциллограммах, то оно у Вас ~0.8мс, у меня было на старой прошивке ~0.03мс.

Вы имеете в виду бинарник latencymeter_old.hex? Или была прошивка ещё первее? Просто два последних скрина в моём первом сообщении - это именно эта прошивка и там фронт импульса на фоторезисторе нарастает в диапазоне от 0,3 до 0,75мс. Я думаю, это скорострельность самого фоторезистора. Не смотря на то, что фронт параболический, можно всё-таки приближённо грубо взять за скорость нарастания фронта 0,2мс/В. И это даже компенсировать никак не надо, поскольку разрешение самого прибора 1мс. Меня больше волнует, почему идёт накопление задержки до 2 и даже изредка до 3мс.

> Попробуйте закомментировать ресурсную функцию расчета медианы в latencymeter.h:90.

Ооо... Вы как разработчик интуитивно чувствуете, где может быть засада! Отключение расчёта медианы стабилизировало длительность свечения светодиода. И она составила примерно 0,5мс.

![04_1](https://github.com/githubniko/LatencyMeter/assets/25266563/2a6dfd17-c9b8-496a-a0b6-8d98b5166d08)

> Так же можно попробовать исключить конденсатор С1 на фоторезисторе.

Это я пробовал. На последней прошивке его влияние уловить трудно, практически невозможно. Я не смог! А вот на бинарнике latencymeter_old.hex чётко видно, что конденсатор увеличивает время между вспышками светодиода. Ниже скрины с конденсатором и без.

![04_2](https://github.com/githubniko/LatencyMeter/assets/25266563/39ccfa5e-7ff0-436a-b94c-369bc6b99363)
![04_3](https://github.com/githubniko/LatencyMeter/assets/25266563/f9390db8-0c90-44c9-afd4-8545d4f74d9d)

> Еще важно, чтобы на фоторезистор не поступал лишний свет.

Да, я тоже это заметил. Лишний свет увеличивает "нулевую" задержку, т.к. реакция фоторезистора - это левая часть перевёрнутой параболы,

![04_4](https://github.com/githubniko/LatencyMeter/assets/25266563/a2edb3b2-9a82-4180-9dc4-9e519dc0db76)

то "лишний" свет поднимает вверх по этой параболе рабочий участок и таким образом увеличивает время реакции фоторезистора. Я эту проблему решил, соединив фоторезистор со светодиодом бумажным тубусом.

![04_5](https://github.com/githubniko/LatencyMeter/assets/25266563/4260afe2-532a-414f-b0ba-dec4da6894d0)

> Почему-то у Вас напряжение на фотодиоде очень большое. Должно быть стартовое +0.5В. Установлено ли Uref = 3.3 ?

Да, установлено. Вывод REF наны соединён с выводом 3V3 и на данный момент там напряжение 3,236 В. Возможно, мне следует уменьшить сопротивление резистора R5. Это который 10к. Мой фоторезистор в темноте имеет сопротивление порядка 100к, а при ярком освещении - около 1к. Это обычный фоторезистор из комплекта Arduino Ultimate Uno R3 Starter Kit.

**Comment by KimIV** [comment]
> Попробуйте закомментировать ресурсную функцию расчета медианы в latencymeter.h:90.

Я посидел над кодом, поразмышлял и мне стала понятная природа плавного нарастания времени свечения светодиода. Это происходит из-за увеличения списка данных, которые используются при расчёте медианы. Время работы функции median() прямопропорционально количеству данных, которое постепенно увеличивается. И что важно, это никак не влияет на "нулевую" задержку. То есть при плавном увеличении времени свечения светодиода мы всё равно можем наблюдать резкие скачки этого времени туда-сюда. А когда смотрим в монитор порта (туда пишет Serial.println(value); (latencymeter.h:119)), то видим цифры 0, 1, 2. Кстати, после того, как я соединил тубусом фоторезистор и светодиод перестала проскакивать цифра 3. И этот факт возвращает к мысли, что быстродействие фоторезистора может быть той самой собакой, которая порылась )))

**Comment by KimIV** [comment]
После замены функции millis() на [micros()](https://github.com/githubniko/LatencyMeter/pull/3/commits/135b7523a1be15ed3dfb1190a304873c977ac3e8) я посмотрел осциллографом импульсы в тех же точках, которые указывал в первом сообщении. И вот, что увидел. Длительность свечения светодиода плавно растёт с момента старта измерений с 0,8 мс до 12 мс и далее стабилизируется. Изменение происходит только в первые 30 секунд. После этого длительность импульса постоянна и если точно составляет 11,88 мс.

![06_1](https://github.com/githubniko/LatencyMeter/assets/25266563/b6428390-52b3-4b36-9396-de9e351680d4)

[Ссылка на видео](https://youtu.be/riIVxjTF750), демонстрирующее процесс.

Меня лично вот это стартовое нарастание длительности свечения светодиода уже мало беспокоит. Главное, что удалось устранить непонятные скачки длительности свечения и нулевой задержки.

Что ещё имею сообщить? Для проверки я выводил в serial разницу между micros() и _timer, то есть до деления на 1000 для получения миллисекунд.

`                valueTime = (micros() - _timer) / 1000; // Считаем задержку`
`                Serial.print(micros() - _timer, DEC);`
`                Serial.print(' ');`
`                AddValue(valueTime);`

Так вот диапазон этих значений для нулевой задержки от 340 до 368 на довольно большой выборке (несколько тысяч). А типовое значение равно 344.
