### ISSUE TITLE
Latency Meter. Неустойчивость LOW.

### ISSUE THREAD

**Issue by KimIV** [githubniko/LatencyMeter#2]
Я обнаружил ещё одну проблему. Но прежде, чем изложить её суть, предлагаю договориться о терминах. Предлагаю называть нулевой задержкой ситуацию, при которой светодиод направлен на фоторезистор либо в полной темноте, либо через тубус, который исключает попадание на фоторезистор постороннего света. Например, у меня это реализовано вот так.

![01_1](https://github.com/githubniko/LatencyMeter/assets/25266563/4f7b90db-92bf-46b0-8793-72fb61ba8675)

Теперь суть проблемы. Я заметил, что при нулевой задержке скачет значение LOW. Я считаю, что LOW в данном случае всегда должно быть равно нулю. Вот ссылка на видео, демонстрирующее скачки LOW. То 0 (ноль), то 1 (единица).

https://youtu.be/nGoV20tnr8o

PS. Версия скетча последняя с закомментированным расчётом медианы
latencymeter.h:90`//                medianTime = round(median());`

**Comment by githubniko** [comment]
Спасибо. Это баг. см latencymeter.h:84
Будет возникать когда minTime = 0.

Заднюю часть светодиода желательно закрасить черной краской.

**Comment by githubniko** [comment]
Заднюю часть светодиода желательно закрасить черной краской.
